name: NerKubKnockBackFFA
version: '${project.version}'
main: cz.nerkub.NerKubKnockBackFFA.NerKubKnockBackFFA
api-version: '1.20'

depend: ["PlaceholderAPI"]

commands:
  knbffa:
    description: Mother of all KNBFFA Commands
    usage: /<command>

permissions:
  knbffa.admin:
    description: Permission for server admins
    default: op