name: NerKubKnockBackFFA
version: '${project.version}'
main: cz.nerkub.NerKubKnockBackFFA.NerKubKnockBackFFA
api-version: '1.20'

commands:
  knbffa:
    description: Mother of all KNBFFA Commands
    usage: /<command>