# If set to true, when a player joins the server, they will spawn at the arena spawn position.
bungee-mode: true

database:
  host: "localhost"
  port: 3306
  name: "my_database"
  username: "username"
  password: "123456789"

# Time (in minutes) after which players will be teleported to the new arena
arena-time: 15

# block-break-time is in seconds.
block-break-time: 3 #Each break phase will last 3 seconds, which means the block will completely break after 12 seconds.

# The Y position at which a player dies when knocked into the void. Can be -10 or 10 (only full numbers).
death-height: 0

# TODO join-message true/false. If true, take join message from messages.yml
join-message: true

# TODO leave-message true/false. If true, take leave message from messages.yml
leave-message: true

# The maximum number of Ender Pearls a player can hold at one time.
max-ender-pearls: 5

# The maximum number of Arrows a player can hold at one time.
max-arrows: 3

# If set to true, players will see bossbar
boss-bar: true

# default-amount - The amount of blocks the player will have when they die or join the server
# on-kill-reward - The amount of blocks the player will receive when they kill someone
build-blocks:
  default-amount: 16
  on-kill-reward: 4
  max-amount: 32

# ScoreBoard
# %knbffa_rank% returns the player's rank
# %knbffa_coins% returns the player's coins
# %knbffa_elo% returns the player's elo
# %knbffa_kills% returns the player's total kills
# %knbffa_deaths% returns the player's total deaths
# %knbffa_kd% returns the player's kill/death ratio (KD)
# %knbffa_killstreak% returns the player's current kill streak
# %knbffa_maxkillstreak% returns the player's highest kill streak
# %knbffa_currentarena% returns the name of the arena the player is currently in
# %knbffa_nextarenain% returns the time until the next arena starts
scoreboard:
  title: '&a&lKnockBackFFA'
  lines:
    15: 'Rank: &b%knbffa_rank%'
    14: 'Coins: &e%knbffa_coins%'
    13: 'Elo: &c%knbffa_elo%'
    12: ''
    11: 'Kills: &a%knbffa_kills%'
    10: 'Deaths: &c%knbffa_deaths%'
    9: 'KD: &e%knbffa_kd%'
    8: ''
    7: 'KillStreak: &a%knbffa_killstreak%'
    6: 'Max KillStreak: &a%knbffa_maxkillstreak%'
    5: ''
    4: 'Arena: &b%knbffa_currentarena%'
    3: 'Next Arena In: &e%knbffa_nextarenain%'
    2: ''
    1: '     &3your.server.ip'

# The amount of ELO a player will gain for killing another player, or the amount that will be deducted if they die.
elo:
  kill-min: 3
  kill-max: 7
  death-min: 2
  death-max: 5

coins:
  kill-min: 3
  kill-max: 10
  kill-streak: 5

# This is the radius around the arena spawn where players are not allowed to attack others and build blocks
safe-zone-radius: 15

doublejump:
  # Cooldown in seconds
  cooldown: 5
  power: 1.3