name: NerKubKnockBackFFA
version: '1.0.0'
main: cz.nerkub.NerKubKnockBackFFA.NerKubKnockBackFFA
api-version: '1.20'

depend: ["PlaceholderAPI"]

commands:
  knbffa:
    description: Mother of all KNBFFA Commands
    usage: /<command>